# Generated by Django 2.0 on 2019-07-31 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_purbeurre', '0011_auto_20190331_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='commentary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_purbeurre.Commentary'),
        ),
        migrations.AddField(
            model_name='user',
            name='commentary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_purbeurre.Commentary'),
        ),
    ]
