# Generated by Django 2.0 on 2019-07-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purbeurre', '0012_auto_20190731_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='com_date',
            field=models.DateField(null=True),
        ),
    ]
