# Generated by Django 2.0 on 2019-08-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_purbeurre', '0014_auto_20190807_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='users_com',
            field=models.IntegerField(),
        ),
    ]
