# Generated by Django 2.0 on 2019-08-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_purbeurre', '0015_auto_20190811_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='users_com',
        ),
    ]
